{{- if .Values.certManagerRbac.operatorWorkaround.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-addl-signers-approve-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-addl-signers-approve
subjects:
- kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
{{- end }}
