apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncm-issuer-utils
  labels:
    app: ncm-issuer-utils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncm-issuer-utils
  template:
    metadata:
      labels:
        app: ncm-issuer-utils
    spec:
      containers:
      - name: "ncm-issuer-utils"
        command: ["/usr/sbin/init"]
        image: ghcr.io/nokia/ncm-issuer-utils:1.2.2
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 998
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_RAW
            - NET_ADMIN
            - SYS_PTRACE
          seccompProfile:
            type: RuntimeDefault
