name: e2e-limited
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  go-versions:
    name: "lookup go versions"
    runs-on: ubuntu-latest
    outputs:
      go-mod-version: ${{ steps.versions.outputs.go-mod-version }}
    steps:
      - uses: actions/checkout@v4
      - uses: arnested/go-version-action@v1
        id: versions
  build-image:
    name: "build ncm-issuer docker image"
    runs-on: ubuntu-latest
    needs: go-versions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - name: "build ncm-issuer image and save to docker image"
        run: |
          make docker-build
          docker save ncm-issuer > ncm-issuer-image.tar
          echo "ncm-issuer image built and saved to ncm-issuer-image.tar"
      - name: "Upload ncm-issuer image"
        uses: actions/upload-artifact@v4
        with:
          name: ncm-issuer-image
          path: ncm-issuer-image.tar
          retention-days: 1

  clientauth:
    name: "clientauth test limited"
    needs: [go-versions, build-image]
    uses: ./.github/workflows/clientauth-test-limited.yml
    secrets: inherit
    with:
      go-version: ${{ fromJSON(needs.go-versions.outputs.go-mod-version) }}
      image-artifact-name: ncm-issuer-image
